name: Build & Release Edge

on:
  push:
    branches:
      - "main"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.3
      - name: Compile for all platforms
        run: |
          deno task build
          deno task server:zip:linux-x86_64
          deno task server:zip:linux-aarch64
          deno task server:zip:darwin-x86_64
          deno task server:zip:darwin-aarch64
          deno task server:zip:windows-x86_64
      - name: Update edge release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          tag_name: edge
          body: Automated build from commit ${{ github.sha }}
          prerelease: true
          files: |
            website/CHANGELOG.md
            dist/plug-compile.js
            dist/silverbullet.js
            silverbullet-*.zip
